<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-19T03:13:14 EDT" name="Surefire suite" finished-at="2021-09-19T03:13:24 EDT" duration-ms="10124">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper, io.cucumber.testng.FeatureWrapper)[pri:0, instance:TestRunnner@7dc222ae]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2021-09-19T03:13:14 EDT" name="Surefire test" finished-at="2021-09-19T03:13:24 EDT" duration-ms="10124">
      <class name="TestRunnner">
        <test-method is-config="true" signature="setUpClass()[pri:0, instance:TestRunnner@7dc222ae]" started-at="2021-09-19T03:13:14 EDT" name="setUpClass" finished-at="2021-09-19T03:13:14 EDT" duration-ms="340" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper, io.cucumber.testng.FeatureWrapper)[pri:0, instance:TestRunnner@7dc222ae]" started-at="2021-09-19T03:13:14 EDT" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2021-09-19T03:13:24 EDT" duration-ms="9675" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User should be able to Sign Up with the valid email adress"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Optional[TalentTek Sign Up feature test suite.]"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Validation error] but found [➥Validation Errors
Th]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Validation error] but found [➥Validation Errors
Th]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at pageobject.Signup_page.asserterrorMessage(Signup_page.java:129)
at stepdefinations.SignUp.ienterstudentinformationwithvalidEmailAdress(SignUp.java:38)
at ✽.I enter student information with valid email adress(file:///Users/sanjidaafrin/Documents/CucumberBDD_Fw/src/test/java/feature/signup/SignUp.feature:6)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:TestRunnner@7dc222ae]" started-at="2021-09-19T03:13:24 EDT" name="tearDownClass" finished-at="2021-09-19T03:13:24 EDT" duration-ms="77" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- TestRunnner -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
